version: 0.2

env:
  variables:
      BB_REPO: "cf-v2"
phases:
  install:
    commands:
      # Setup Docker
#      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
#      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
      - eval $(aws ecr --no-include-email get-login)
  pre_build:
    commands:
      - export GIT_SHORT_ID="$(git rev-parse --short HEAD)"
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - echo "$ACCOUNT_ID"
      - echo "$AWS_REGION"
      - echo "$REPO"
      - echo "$TAG"
  build:
    commands:
      - docker build -t puppeteer .
      - docker tag puppeteer:latest 163859100295.dkr.ecr.us-west-2.amazonaws.com/puppeteer:latest
  post_build:
    commands:
      - docker push $(ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(REPO):$(TAG)
artifacts:
    files:
      - '**/*'
