version: 0.2

env:
  variables:
      BB_REPO: "cf-v2"
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - docker build -t "$REPO:$TAG" .
      - docker tag "$REPO:$TAG" "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO:$TAG"
      - docker run --rm --privileged "$REPO:$TAG" node node_modules/.bin/jest tests/test.js
  post_build:
    commands:
      - if [ -z "$CODEBUILD_BUILD_SUCCEEDING" ]; docker push "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO:$TAG"
artifacts:
    files:
      - '**/*'
