Parameters:
  RepoName:
    Type: String
Resources:
  DockerRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref RepoName
Outputs:
  Arn:
    Value: !GetAtt DockerRepository.Arn
